
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module AudioPWM(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// VGA //////////
	output		     [3:0]		VGA_B,
	output		     [3:0]		VGA_G,
	output		          		VGA_HS,
	output		     [3:0]		VGA_R,
	output		          		VGA_VS,

	//////////// GPIO, GPIO connect to GPIO Default //////////
	inout 		    [35:0]		GPIO
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
wire clk_audio;

pll_audio pll( .inclk0( MAX10_CLK1_50), .c0( clk_audio), .locked(LEDR[0])); // remains at 50MHz

PWM_Controller pwm ( .PWM_CW( SW[9:0]), .PWM_out( LEDR[1]), .clk(clk_audio)); 




//=======================================================
//  Structural coding
//=======================================================



endmodule
